### ISSUE TITLE
Lift instances for `NonEmpty` and `Void`.

### ISSUE THREAD

**Issue by phadej** [bennofs/th-lift-instances#12]
This instances would be good to be here, for `base` / `template-haskell` versions where they don't have it.

Next `void` and `semigroups` will have these instances, providing them when they are not in `base`.

I can make a PR.

Related:
- https://github.com/ekmett/semigroups/issues/89
- https://github.com/ekmett/void/issues/16 

cc @RyanGlScott

**Comment by bennofs** [comment]
Seems like a good idea, happy to accept a PR.
