### ISSUE TITLE
Release version 0.1.19 to hackage & stackage

### ISSUE THREAD

**Issue by recursion-ninja** [bennofs/th-lift-instances#28]
It seems that the last commit to `master` is stable and it would be nice to build with `th-lift-instances` using `ghc-9.0.1` while not having to rely on a pinned commit of the dependency in the `cabal.project` and/or `stack.yaml` file(s).

**Comment by bennofs** [comment]
The released 0.1.18 version shoud have all commits from master: https://github.com/bennofs/th-lift-instances/releases/tag/v0.1.18
