### ISSUE TITLE
Instances for ByteString lead to long compile times and lots of memory usage

### ISSUE THREAD

**Issue by mgsloan** [bennofs/th-lift-instances#4]
``` haskell
{-# LANGUAGE TemplateHaskell #-}
import qualified Data.ByteString as BS
import qualified Data.ByteString.Char8 as BSC
import System.IO.Unsafe (unsafePerformIO)
import Data.ByteString.Unsafe (unsafePackAddressLen)
import Language.Haskell.TH
import Language.Haskell.TH.Syntax
import Data.Word (Word8)
```

With code similar to what th-lift-instances uses:

``` haskell
main :: IO ()
main = BSC.putStrLn
    $([|BS.pack $(lift (replicate 65536 42 :: [Word8]))|])
```

`time stack ghc -- --make th-lift-instances-test1.hs` in [th-utilities](https://github.com/fpco/th-utilities) yields

```
[1 of 1] Compiling Main             ( th-lift-instances-test1.hs, th-lift-instances-test1.o )
^C^C

real    1m11.212s
user    0m56.148s
sys 0m1.824s
```

I had to cancel it because I was running out of memory and my computer was getting sluggish.

Instead, something like the following should be used:

``` haskell
main :: IO ()
main = BSC.putStrLn
    $([|unsafePerformIO (unsafePackAddressLen 65536 $(litE (stringPrimL (replicate 65536 42))))|])
```

yields

```
[1 of 1] Compiling Main             ( th-lift-instances-test2.hs, th-lift-instances-test2.o )
Linking th-lift-instances-test2 ...

real    0m1.324s
user    0m0.980s
sys 0m0.152s
```

**Comment by mgsloan** [comment]
I'm working on a PR for this

**Comment by mgsloan** [comment]
BTW, I have not forgotten about this.  Plan is to put the requisite utilities into `store-core` and make it a dep of `th-lift-instances`.

**Comment by phadej** [comment]
Does `store-core` works with GHCJS, related to #9 ?

**Comment by mgsloan** [comment]
Last time I checked most of store works with ghcjs:
https://github.com/fpco/store/issues/43 . Main exception is the instance
for integer, but that should be straightforward to fix if it's needed.
